// app/constants/games.ts
import type { Asset } from "@/other/types/asset";

// NB:
// - Renommé gameItemsByGameId -> assetsByGameId
// - Types alignés sur Asset (id:string, count:number, price:number, gameId:string, gameOwner:string, metaData)
// - Rareté et image stockées dans metaData (name: "rarity" et name: "image")
// - Ids dédupliqués (le 110 apparaissait 3x)

export const assetsByGameId: Record<string, Asset[]> = {
  "1": [
    {
      id: "101",
      name: "Dragon Slayer",
      description: "Épée mythique qui aboie sur les wyvernes.",
      count: 1,
      price: 250,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "102",
      name: "Iron Shield",
      description: "Bouclier solide, compatible avec les fuites stratégiques.",
      count: 1,
      price: 30,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "103",
      name: "Runic Bow",
      description: "Arc gravé de runes, siffle quand tu tires.",
      count: 1,
      price: 95,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "104",
      name: "Ember Staff",
      description: "Bâton qui chauffe les mains et les trolls.",
      count: 1,
      price: 220,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "105",
      name: "Frost Dagger",
      description: "Dague glacée pour gestes froids et rapides.",
      count: 1,
      price: 72,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "106",
      name: "Traveler Cloak",
      description: "Cape confortable, +2 au style.",
      count: 1,
      price: 18,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "107",
      name: "Wyvern Helm",
      description: "Casque orné d’écaille, léger comme un mensonge.",
      count: 1,
      price: 110,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "108",
      name: "Crystal Orb",
      description: "Voit l’avenir. Spoiler: tu dépenses trop.",
      count: 1,
      price: 280,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "109",
      name: "Oak Shield",
      description: "Bouclier en chêne qui sent la forêt.",
      count: 1,
      price: 24,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "110",
      name: "Thunder Hammer",
      description: "Marteau qui gronde quand on bâille.",
      count: 1,
      price: 260,
      gameId: "1",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
  ],
  "2": [
    {
      id: "201",
      name: "Crystal Wand",
      description: "Baguette translucide, cliquetis satisfaisant.",
      count: 1,
      price: 90,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://purepng.com/public/uploads/large/fortnite-new-galaxy-skin-gm0.png", renderingMetaData: [] },
      ],
    },
    {
      id: "202",
      name: "Rune Grimoire",
      description: "Livre de sorts, pages qui se tournent toutes seules.",
      count: 1,
      price: 75,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "203",
      name: "Moon Amulet",
      description: "Amulette argentée, protège des cauchemars.",
      count: 1,
      price: 22,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "204",
      name: "Illusion Cape",
      description: "Cape d’illusion, disparaît quand on te regarde.",
      count: 1,
      price: 68,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "205",
      name: "Arcane Lens",
      description: "Lunettes qui révèlent glyphes et cernes.",
      count: 1,
      price: 19,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "206",
      name: "Elder Scepter",
      description: "Sceptre cérémoniel, aussi lourd que l’ego.",
      count: 1,
      price: 230,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "207",
      name: "Portal Key",
      description: "Clé multidimensionnelle, se perd ailleurs.",
      count: 1,
      price: 120,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "208",
      name: "Mirror Shard",
      description: "Renvoie les sorts et ton regard gêné.",
      count: 1,
      price: 28,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "209",
      name: "Phoenix Feather",
      description: "Plume tiède, rallume l’espoir.",
      count: 1,
      price: 310,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "210",
      name: "Golem Pebble",
      description: "Caillou de golem. Oui, un caillou.",
      count: 1,
      price: 7,
      gameId: "2",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
  ],
  "3": [
    {
      id: "301",
      name: "Cyber Blade",
      description: "Katana ionique. Coupe les connexions instables.",
      count: 1,
      price: 300,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "302",
      name: "Pulse Pistol",
      description: "Pistolet à impulsions, bruit satisfaisant.",
      count: 1,
      price: 105,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "303",
      name: "Drone Buddy",
      description: "Petit drone qui fait bip. Et pas que.",
      count: 1,
      price: 140,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "304",
      name: "Neon Visor",
      description: "Visière filtrante, +10 synthwave.",
      count: 1,
      price: 26,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "305",
      name: "EMP Grenade",
      description: "Éteint les lumières et l’ambiance.",
      count: 1,
      price: 65,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "306",
      name: "Nano Armor",
      description: "Armure adaptative. Câlins non inclus.",
      count: 1,
      price: 340,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "307",
      name: "Holo Emitter",
      description: "Projette des leurres moins jugeants.",
      count: 1,
      price: 33,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "308",
      name: "Circuit Dagger",
      description: "Lame imprimée, tient chaud l’hiver.",
      count: 1,
      price: 88,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "rare", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "309",
      name: "Data Cube",
      description: "Cube mémoire, clignote pour faire sérieux.",
      count: 1,
      price: 15,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "common", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
    {
      id: "310",
      name: "Quantum Core",
      description: "Cœur quantique instable. Comme le lundi.",
      count: 1,
      price: 420,
      gameId: "3",
      gameOwner: "",
      metaData: [
        { name: "rarity", value: "legendary", renderingMetaData: [] },
        { name: "image", value: "https://th.bing.com/th/id/R.dcac0f4287b6eba2a325ff0a82c3e61b?rik=LJMv0WEL1Yst9A&riu=http%3a%2f%2fwww.pngall.com%2fwp-content%2fuploads%2f4%2fFortnite-Skin-PNG-Download-Image.png&ehk=CzrxLgTzB6Vk1VxeqM9yTtIeyUOK5lu1LYiVZ8P2njY%3d&risl=&pid=ImgRaw&r=0", renderingMetaData: [] },
      ],
    },
  ],
};
